apiVersion: v2
name: mcp-server-factset
description: An experimental MCP server for Factset.
type: application
version: 0.2.1 # TODO: Tag must be auto-injected via release process from package.json
appVersion: 0.2.1 # FIXME: this does not work as intended sadly, this version does not trickle down into the dependency
dependencies:
  - alias: server
    name: backend-service
    repository: oci://ghcr.io/unique-ag/helm-charts
    version: ~5.4.2
