name: "[mcp/server/outlook] Publish"

on:
  push:
    branches:
      - main
    paths:
      - services/outlook-mcp/**
      - .github/workflows/outlook.server.mcp.cd.yaml
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/_template-mcp-cd.yaml
    with:
      service-name: outlook
      service-path: services/outlook-mcp